legends = [
    "Bloodhound",
    "Gibraltar",
    "Lifeline",
    "Pathfinder",
    "Seer",
    "Wraith",
    "Bangalore",
    "Caustic",
    "Mirage",
    "Octane",
    "Wattson",
    "Crypto",
    "Revenant",
    "Loba",
    "Rampart",
    "Horizon",
    "Fuse",
    "Valkyrie",
    "Ash",
    "Mad Maggie",
    "Newcastle",
    "Vantage",
    "Catalyst",
    "Ballistic",
    "Conduit",
    "Alter",
    "Sparrow"
]

weapons = [
    "R‑301 Carbine",
    "Flatline",
    "Hemlok Burst AR",
    "Havoc Rifle",
    "Volt SMG",
    "R‑99 SMG",
    "Alternator SMG",
    "CAR SMG",
    "Prowler Burst PDW",
    "Mastiff Shotgun",
    "EVA‑8 Auto",
    "Mozambique Shotgun",
    "Sentinel",
    "Longbow DMR",
    "30‑30 Repeater",
    "Charge Rifle",
    "Bocek Compound Bow",
    "Wingman",
    "P2020",
    "RE‑45 Auto",
    "Devotion LMG",
    "L‑STAR EMG",
    "Spitfire LMG",
    "Rampage LMG",
    "M600 Spitfire"
]